// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class LoginConexaoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginConexao() {
    driver.get("https://conexaoqa.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1294, 1040));
    assertThat(driver.findElement(By.cssSelector("*[data-test=\"navbar-conexaoQA\"]")).getText(), is("ConexãoQA"));
    assertThat(driver.findElement(By.cssSelector("*[data-test=\"landing-login\"]")).getText(), is("Login"));
    driver.findElement(By.cssSelector("*[data-test=\"landing-login\"]")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("schermack07tiago@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Tiago125");
    driver.findElement(By.cssSelector("*[data-test=\"login-submit\"]")).click();
  }
}
